const STRINGS = {
  century: "century",
  centuries: "centuries",
  decade: "decade",
  decades: "decades",
  millennium: "millennium",
  millennia: "millennia",
  year: "year",
  years: "years",
  month: "month",
  months: "months",
  week: "week",
  weeks: "weeks",
  day: "day",
  days: "days",
  hour: "hour",
  hours: "hours",
  minute: "minute",
  minutes: "minutes",
  second: "second",
  seconds: "seconds",
  millisecond: "millisecond",
  milliseconds: "milliseconds",
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
  mon: "mon",
  tue: "tue",
  wed: "wed",
  thu: "thu",
  fri: "fri",
  sat: "sat",
  sun: "sun",
  january: "january",
  february: "february",
  march: "march",
  april: "april",
  may: "may",
  june: "june",
  july: "july",
  august: "august",
  september: "september",
  october: "october",
  november: "november",
  december: "december",
  jan: "jan",
  feb: "feb",
  mar: "mar",
  apr: "apr",
  jun: "jun",
  jul: "jul",
  aug: "aug",
  sep: "sep",
  oct: "oct",
  nov: "nov",
  dec: "dec",
  am: "am",
  pm: "pm",
  millisecondAbbr: "",
} as const;

export const milleniumToOrdinal = (text: string): number => {
  return parseInt(text, 10);
};
